# -*- coding: utf-8 -*-
"""LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z154_wyPA96SdmyzNlu6JtBhT4wuNjnR
"""

from typing import Tuple
# create a list of integers
numbers = [10, 23, 5, 89, 45, 67, 34, 22, 11, 90]

print('orignal List', numbers)

# Sum, Max, and min
print('Sum:', sum(numbers))
print('Max:', max(numbers))
print('Min:', min(numbers))

# Add and Remove elemnet
numbers.append(50)
numbers.remove(23)
print('Update List:', numbers)

# Sort ascending and descending
print('Ascending:', sorted(numbers))
print('Descending:', sorted(numbers, reverse=True))

# Tuple with 5 String
Fruit = ('Apple', 'Banana', 'Orange', 'Mango', 'Kiwi')
print('Tuple', Fruit)
print('Second_Element', Fruit[1])
print('Last_Element', Fruit[-1])

# For Modification lets convert Tuple into list
fruit_list = list(Fruit)
fruit_list[2] = 'Avacado'
print('Modified_List:', fruit_list)

# Sets with Some Common and Unique Elements (Union , Intersection, Difference )
set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}

print('Union', set_a | set_b)
print('Intersection', set_a & set_b)
print('Difference', set_a - set_b)

# Create Dictionary
Students = {'Zoraiz': 85, 'Naima': 90, 'Ahmad': 78, 'Aqsa': 92, 'Umar': 89}
print('Dictionary : ', Students)

# Print Keys and Values
print('Keys', Students.keys())
print('Values', Students.values())

# Update Value
Students['Zoraiz'] = 100
print('Updated Dictionary:', Students)