# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFpNWKvYy2Yq0E2TTOaFG8Dp7q7ImnLi
"""

import numpy as np

# Create 1D array
arr = np.arange(7, 37)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(5, 6)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(31, 61)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)